version: '3.7'
services:
  ###############################################################
  #    Postgres database
  ###############################################################
  postgres:
    image: tarjei400/postgress:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: admin
      POSTGRESQL_PASSWORD: admin

      POSTGRES_DB: boilerplate
      POSTGRESQL_PGAUDIT_LOG_CATALOG: 'on'
      POSTGRESQL_PGAUDIT_LOG_PARAMETER: 'on'
      POSTGRESQL_PGAUDIT_LOG: read, write, ddl
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: root
      POSTGRESQL_REPLICATION_PASSWORD: admin
      POSTGRESQL_WAL_LEVEL: logical

    networks:
      - intranet

  ###############################################################
  #    RabbitMQ
  ###############################################################

  rabbitmq:
    image: bitnami/rabbitmq:3.10
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.10.0/rabbitmq_delayed_message_exchange-3.10.0.ez
      - RABBITMQ_PLUGINS=rabbitmq_delayed_message_exchange, rabbitmq_management

    networks:
      - intranet

  ###############################################################
  #    Kafka compatible lightweight engine
  ###############################################################


  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    # NOTE: Please use the latest version here!
    build:
      dockerfile: redpanda.Dockerfile
      context: ./docker
    container_name: redpanda-1
    networks:
      - intranet
    ports:
      - 9092:9092
      - 29092:29092

  ###############################################################
  #    StateFun runtime
  ###############################################################
#
#  statefun-manager:
#    image: apache/flink-statefun:3.2.0
#    expose:
#      - "6123"
#    ports:
#      - "8082:8081"
#    environment:
#      ROLE: master
#      MASTER_HOST: statefun-manager
#    networks:
#      - intranet
#    volumes:
#      - ./module.yaml:/opt/statefun/modules/workshop/module.yaml
#      - ./flink:/opt/flink/conf
#
#  statefun-worker:
#    image: apache/flink-statefun:3.2.0
#    expose:
#      - "6121"
#      - "6122"
#    networks:
#      - intranet
#    environment:
#      ROLE: worker
#      MASTER_HOST: statefun-manager
#    volumes:
#      - ./module.yaml:/opt/statefun/modules/workshop/module.yaml
#      - ./flink:/opt/flink/conf

#  app:
#    build:
#      context: ./
#    ports:
#      - "8080:8080"
#
#    volumes:
#      - ./config/application.yaml:/var/application/config/application.yaml
#
#    restart: always
#    environment:
#      NODE_ENV: "docker-compose"
#
#    networks:
#      - intranet

networks:
  intranet:
