export const PROXY_FIELD_DEFAULTS = 'PROXY_FIELD_DEFAULTS_METADATA';
export const PROXY_FIELD_GETTERS = 'PROXY_FIELD_GETTERS_METADATA';
export const PROXY_FIELD_GETTER_FINISHERS = 'PROXY_FIELD_GETTER_FINISHERS_METADATA';
export const PROXY_FIELD_SETTERS = 'PROXY_FIELD_SETTERS_METADATA';
export const PROXY_MODULE_ASSOCIATION = 'PROXY_MODULE_ASSOCIATION';
export const FACTORY_USED_METHOD_NAME = 'FACTORY_USED_METHOD_NAME';
