export const PROXY_FIELD_DEFAULTS = 'PROXY_FIELD_DEFAULTS_METADATA';
export const PROXY_INJECT_DEPS = 'PROXY_INJECT_DEPS';

export const BEAN_METHOD_ARGS_METADATA_KEY = 'BEAN_METHOD_ARGS_METADATA_KEY';
export const ADVICE_EXTERNAL_CONTEXT = 'DISCOVERY_MODULE_ADVICE_EXTERNAL_CONTEXT';
export const ADVICE_EXTERNAL_CONTEXT_TYPE = 'DISCOVERY_MODULE_ADVICE_EXTERNAL_CONTEXT_TYPE';
export const ADVICES_BEFORE = 'DISCOVERY_MODULE_ADVICES_BEFORE';
export const ADVICES_CALL_WRAPPER = 'DISCOVERY_MODULE_ADVICES_CALL_WRAPPER';
export const ADVICES_AFTER = 'DISCOVERY_MODULE_ADVICES_AFTER';
export const ADVICES_AFTER_CONSTRUCTOR = 'ADVICES_AFTER_CONSTRUCTOR';
export const ADVICES_AFTER_THROW = 'DISCOVERY_MODULE_ADVICES_AFTER_THROW';
export const ADVICES_SETTER_BEFORE = 'DISCOVERY_MODULE_ADVICES_SETTER_BEFORE';
export const ADVICES_SETTER_AFTER = 'DISCOVERY_MODULE_ADVICES_SETTER_AFTER';
export const ADVICES_SETTER_AFTER_THROW =
  'DISCOVERY_MODULE_ADVICES_SETTER_AFTER_THROW';
export const ADVICES_BELONGS_TO = 'DISCOVERY_MODULE_ADVICES_BELONGS_TO';
export const ADVICES_INJECT_FACTOR = 'DISCOVERY_MODULE_INJECT_FACTORY';
export const ADVICES_ENSURE_PARENT_IMPORTS =
  'DISCOVERY_MODULE_ADVICES_ENSURE_PARENT_IMPORTS';
export const ADVICES_TRACED =
  'DISCOVERY_MODULE_ADVICES_TRACED';
export const MODULE_CONTAINER =
  'DISCOVERY_MODULE_MODULE_CONTAINER';
export const FACTORY_USED_METHOD_NAME = 'FACTORY_USED_METHOD_NAME';

export const SKIP_BEAN_PROXY_TRAPS_FOR = ['constructor', 'then', "toString"];
export const SKIP_IF_NEST_METHODS_ARE_NOT_DEFINED = [
  'onModuleInit',
  'onApplicationBootstrap',
];

export type InjectFactory = {
  inject?: Record<string, any>;
  nonInjectable?: boolean;
  provide?: any;
};
