test:
  inner: 'http://localhost:8888s'
  inner2: 'http://localhost:2'
  inner3:
    a: t
    b: 1
    arr:
      - a: t
        b: 1
        c: 1
      - a: t
        b: t
        c: t
    arr2:
      rec1:
        a: t
        b: 1
        c: 1
      rec2:
        a: t
        b: t
        c: t
